export enum CATEGORIES {
  'Accesorios para mascotas' = 'Accesorios para mascotas',
  'Adiestramiento y deportes caninos' = 'Adiestramiento y deportes caninos',
  'Alimentación' = 'Alimentación',
  'Cremación y servicios funerarios' = 'Cremación y servicios funerarios',
  'Comportamiento y modificación de conducta' = 'Comportamiento y modificación de conducta',
  'Cuidado especial' = 'Cuidado especial',
  'Cuidado nocturno' = 'Cuidado nocturno',
  'Entretenimiento' = 'Entretenimiento',
  'Entierro y cementerio para mascotas' = 'Entierro y cementerio para mascotas',
  'Entrenamiento' = 'Entrenamiento',
  'Entrenamiento online' = 'Entrenamiento online',
  'Espacios para eventos' = 'Espacios para eventos',
  'Fotografía' = 'Fotografía',
  'Higiene dental' = 'Higiene dental',
  'Hospedaje' = 'Hospedaje',
  'Masaje y relajación' = 'Masaje y relajación',
  'Moda y estilismo' = 'Moda y estilismo',
  'Peluquería' = 'Peluquería',
  'Peluquería a domicilio' = 'Peluquería a domicilio',
  'Rehabilitación' = 'Rehabilitación',
  'Salud' = 'Salud',
  'Seguros para mascotas' = 'Seguros para mascotas',
  'Servicios de acicalamiento' = 'Servicios de acicalamiento',
  'Servicios de adopción' = 'Servicios de adopción',
  'Servicios de emergencia' = 'Servicios de emergencia',
  'Servicios de spa para mascotas' = 'Servicios de spa para mascotas',
  'Servicios de terapia asistida con mascotas' = 'Servicios de terapia asistida con mascotas',
  'Tiendas de mascotas y suministros' = 'Tiendas de mascotas y suministros',
}

interface CategoryName {
  name: CATEGORIES
}

export const CATEGORIES_NAME: CategoryName[] = [
  { name: CATEGORIES['Accesorios para mascotas'] },
  { name: CATEGORIES['Adiestramiento y deportes caninos'] },
  { name: CATEGORIES['Alimentación'] },
  { name: CATEGORIES['Cremación y servicios funerarios'] },
  { name: CATEGORIES['Comportamiento y modificación de conducta'] },
  { name: CATEGORIES['Cuidado especial'] },
  { name: CATEGORIES['Cuidado nocturno'] },
  { name: CATEGORIES['Entretenimiento'] },
  { name: CATEGORIES['Entierro y cementerio para mascotas'] },
  { name: CATEGORIES['Entrenamiento'] },
  { name: CATEGORIES['Entrenamiento online'] },
  { name: CATEGORIES['Espacios para eventos'] },
  { name: CATEGORIES['Fotografía'] },
  { name: CATEGORIES['Higiene dental'] },
  { name: CATEGORIES['Hospedaje'] },
  { name: CATEGORIES['Masaje y relajación'] },
  { name: CATEGORIES['Moda y estilismo'] },
  { name: CATEGORIES['Peluquería'] },
  { name: CATEGORIES['Peluquería a domicilio'] },
  { name: CATEGORIES['Rehabilitación'] },
  { name: CATEGORIES['Salud'] },
  { name: CATEGORIES['Seguros para mascotas'] },
  { name: CATEGORIES['Servicios de acicalamiento'] },
  { name: CATEGORIES['Servicios de adopción'] },
  { name: CATEGORIES['Servicios de emergencia'] },
  { name: CATEGORIES['Servicios de spa para mascotas'] },
  { name: CATEGORIES['Servicios de terapia asistida con mascotas'] },
  { name: CATEGORIES['Tiendas de mascotas y suministros'] },
]
