export const statesOfMexico = [
  { value: 'aguascalientes', label: 'Aguascalientes', slug: 'aguascalientes' },
  {
    value: 'baja california',
    label: 'Baja California',
    slug: 'baja-california',
  },
  {
    value: 'baja california-sur',
    label: 'Baja California Sur',
    slug: 'baja-california-sur',
  },
  { value: 'campeche', label: 'Campeche', slug: 'campeche' },
  { value: 'coahuila', label: 'Coahuila', slug: 'coahuila' },
  { value: 'colima', label: 'Colima', slug: 'colima' },
  { value: 'chiapas', label: 'Chiapas', slug: 'chiapas' },
  { value: 'chihuahua', label: 'Chihuahua', slug: 'chihuahua' },
  {
    value: 'ciudad de mexico',
    label: 'Ciudad de México',
    slug: 'ciudad-de-mexico',
  },
  { value: 'durango', label: 'Durango', slug: 'durango' },
  { value: 'guanajuato', label: 'Guanajuato', slug: 'guanajuato' },
  { value: 'guerrero', label: 'Guerrero', slug: 'guerrero' },
  { value: 'hidalgo', label: 'Hidalgo', slug: 'hidalgo' },
  { value: 'jalisco', label: 'Jalisco', slug: 'jalisco' },
  { value: 'estado de mexico', label: 'Estado de México', slug: 'mexico' },
  { value: 'michoacan', label: 'Michoacán', slug: 'michoacan' },
  { value: 'morelos', label: 'Morelos', slug: 'morelos' },
  { value: 'nayarit', label: 'Nayarit', slug: 'nayarit' },
  { value: 'nuevo leon', label: 'Nuevo León', slug: 'nuevo-leon' },
  { value: 'oaxaca', label: 'Oaxaca', slug: 'oaxaca' },
  { value: 'puebla', label: 'Puebla', slug: 'puebla' },
  { value: 'queretaro', label: 'Querétaro', slug: 'queretaro' },
  { value: 'quintana roo', label: 'Quintana Roo', slug: 'quintana-roo' },
  {
    value: 'san luis potosi',
    label: 'San Luis Potosí',
    slug: 'san-luis-potosi',
  },
  { value: 'sinaloa', label: 'Sinaloa', slug: 'sinaloa' },
  { value: 'sonora', label: 'Sonora', slug: 'sonora' },
  { value: 'tabasco', label: 'Tabasco', slug: 'tabasco' },
  { value: 'tamaulipas', label: 'Tamaulipas', slug: 'tamaulipas' },
  { value: 'tlaxcala', label: 'Tlaxcala', slug: 'tlaxcala' },
  { value: 'veracruz', label: 'Veracruz', slug: 'veracruz' },
  { value: 'yucatan', label: 'Yucatán', slug: 'yucatan' },
  { value: 'zacatecas', label: 'Zacatecas', slug: 'zacatecas' },
]
