export const statesOfMexico = [
  { value: 'AGS', label: 'Aguascalientes', slug: 'aguascalientes' },
  { value: 'BCN', label: 'Baja California', slug: 'baja-california' },
  { value: 'BCS', label: 'Baja California Sur', slug: 'baja-california-sur' },
  { value: 'CAM', label: 'Campeche', slug: 'campeche' },
  { value: 'COA', label: 'Coahuila', slug: 'coahuila' },
  { value: 'COL', label: 'Colima', slug: 'colima' },
  { value: 'CHP', label: 'Chiapas', slug: 'chiapas' },
  { value: 'CHH', label: 'Chihuahua', slug: 'chihuahua' },
  { value: 'CMX', label: 'Ciudad de México', slug: 'ciudad-de-mexico' },
  { value: 'DUR', label: 'Durango', slug: 'durango' },
  { value: 'GUA', label: 'Guanajuato', slug: 'guanajuato' },
  { value: 'GRO', label: 'Guerrero', slug: 'guerrero' },
  { value: 'HID', label: 'Hidalgo', slug: 'hidalgo' },
  { value: 'JAL', label: 'Jalisco', slug: 'jalisco' },
  { value: 'MEX', label: 'Estado de México', slug: 'mexico' },
  { value: 'MIC', label: 'Michoacán', slug: 'michoacan' },
  { value: 'MOR', label: 'Morelos', slug: 'morelos' },
  { value: 'NAY', label: 'Nayarit', slug: 'nayarit' },
  { value: 'NLE', label: 'Nuevo León', slug: 'nuevo-leon' },
  { value: 'OAX', label: 'Oaxaca', slug: 'oaxaca' },
  { value: 'PUE', label: 'Puebla', slug: 'puebla' },
  { value: 'QUE', label: 'Querétaro', slug: 'queretaro' },
  { value: 'ROO', label: 'Quintana Roo', slug: 'quintana-roo' },
  { value: 'SLP', label: 'San Luis Potosí', slug: 'san-luis-potosi' },
  { value: 'SIN', label: 'Sinaloa', slug: 'sinaloa' },
  { value: 'SON', label: 'Sonora', slug: 'sonora' },
  { value: 'TAB', label: 'Tabasco', slug: 'tabasco' },
  { value: 'TAM', label: 'Tamaulipas', slug: 'tamaulipas' },
  { value: 'TLA', label: 'Tlaxcala', slug: 'tlaxcala' },
  { value: 'VER', label: 'Veracruz', slug: 'veracruz' },
  { value: 'YUC', label: 'Yucatán', slug: 'yucatan' },
  { value: 'ZAC', label: 'Zacatecas', slug: 'zacatecas' },
]
